export const INIT_SOCKET = 'INIT_SOCKET'
export const DELETE_SOCKET = 'DELETE_SOCKET'

export const ADD_MESSAGE_INFO = 'ADD_MESSAGE_INFO'
export const DELETE_MESSAGE_INFO = 'DELETE_MESSAGE_INFO'

export const ADD_EVENT_INFO = 'ADD_EVENT_INFO'